=== 247687009/tddl/tddl-optimizer/src/main/resources/META-INF/matrix.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="https://github.com/alibaba/tamper/schema/mapping"
	xmlns="https://github.com/alibaba/tamper/schema/mapping" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

    <xs:element name="matrix">
		<xs:annotation>
			<xs:documentation>matrix config</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="group" maxOccurs="unbounded" />
				<xs:element ref="properties" maxOccurs="1" />
			</xs:choice>
			
			<xs:attribute name="name" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>group name</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="group">
		<xs:annotation>
			<xs:documentation>group config</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="atom" maxOccurs="unbounded" />
				<xs:element ref="properties" maxOccurs="1" />
			</xs:choice>

			<xs:attribute name="name" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>group name</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			
			<xs:attribute name="type" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>group name</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="atom">
		<xs:annotation>
			<xs:documentation>atom config</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="properties" maxOccurs="1" />
			</xs:choice>

			<xs:attribute name="name" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>group name</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="properties">
		<xs:annotation>
			<xs:documentation>properties config</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="property" maxOccurs="unbounded" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="property">
		<xs:annotation>
			<xs:documentation>property config</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>property name</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="value" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>property value</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== 247687009/tddl/tddl-qatest/src/test/resources/test_matrix.xml
<?xml version="1.0" encoding="UTF-8"?>
<matrix name="test_matrix" xmlns="https://github.com/tddl/tddl/schema/matrix"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://github.com/tddl/tddl/schema/matrix https://raw.github.com/tddl/tddl/master/tddl-optimizer/src/main/resources/META-INF/matrix.xsd">

	<group name="andor_show_group0" type="MYSQL_JDBC">
		<properties>
			<property name="com.taobao.tddl.jdbc.group_V2.4.1_andor_show_group0">
				<value>andor_show_group0_atom0:r10w10p0</value>
			</property>
		</properties>

		<atom name="andor_show_group0_atom0">

			<properties>
				<property name="com.taobao.tddl.atom.global.andor_show_group0_atom0">
					<value>
					ip=10.232.31.21
					port=3306
					dbName=andor_show
					dbType=mysql
					dbStatus=RW
				</value>
				</property>
				<property
					name="com.taobao.tddl.atom.app.andor_show.andor_show_group0_atom0">
					<value>
					userName=andor
					minPoolSize=20
					maxPoolSize=40
					idleTimeout=20
					blockingTimeout=10000
					preparedStatementCacheSize=1000
					connectionProperties=characterEncoding=gbk;autoReconnect=true
					readRestrictTimes=0
					writeRestrictTimes=0
					timeSliceInMillis=0
				</value>
				</property>

				<property name="com.taobao.tddl.atom.passwd.andor_show.mysql.andor">
					<value>encPasswd=364e198e1cfa74ef</value>
				</property>
			</properties>
		</atom>

		<atom name="">
		</atom>

		<atom name="">
		</atom>
	</group>


	<group name="andor_show_group1" type="MYSQL_JDBC">

	</group>


</matrix>

=== 247687009/tddl/tddl-matrix/src/test/resources/test_matrix.xml
<?xml version="1.0" encoding="UTF-8"?>
<matrix name="test_matrix" xmlns="https://github.com/tddl/tddl/schema/matrix"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://github.com/tddl/tddl/schema/matrix https://raw.github.com/tddl/tddl/master/tddl-optimizer/src/main/resources/META-INF/matrix.xsd">

	<group name="andor_show_group0" type="MYSQL_JDBC">
		<properties>
			<property name="com.taobao.tddl.jdbc.group_V2.4.1_andor_show_group0">
				<value>andor_show_group0_atom0:r10w10p0</value>
			</property>
		</properties>

		<atom name="andor_show_group0_atom0">
			<property name="com.taobao.tddl.atom.global.andor_show_group0_atom0">
				<value>
					ip=10.232.31.21
					port=3306
					dbName=andor_show
					dbType=mysql
					dbStatus=RW
				</value>
			</property>
			<property
				name="com.taobao.tddl.atom.app.andor_show.andor_show_group0_atom0">
				<value>
					userName=andor
					minPoolSize=20
					maxPoolSize=40
					idleTimeout=20
					blockingTimeout=10000
					preparedStatementCacheSize=1000
					connectionProperties=characterEncoding=gbk;autoReconnect=true
					readRestrictTimes=0
					writeRestrictTimes=0
					timeSliceInMillis=0
				</value>
			</property>

			<property name="com.taobao.tddl.atom.passwd.andor_show.mysql.andor">
				<value>encPasswd=364e198e1cfa74ef</value>
			</property>
		</atom>

		<atom name="">
		</atom>

		<atom name="">
		</atom>
	</group>

	<group name="andor_group_1" type="MYSQL_JDBC">
	</group>

	<!-- hbase group -->
	<group name="andor_hbase_group" type="HBASE_CLIENT">
		<properties>
			<property name="mysql_groupName" value="andor_hbase_group" />
			<property name="mysql_appName" value="andor_hbase_qatest" />
			<property name="hbase.zookeeper.quorum" value="10.20.144.51" />
			<property name="hbase.zookeeper.property.clientPort" value="2181" />
			<property name="zookeeper.znode.parent" value="/hbase_tesla" />
		</properties>
	</group>

	<group name="andor_hbase_group2" type="HBASE_CLIENT">
		<properties>
			<property name="mysql_groupName" value="andor_hbase_group2" />
			<property name="mysql_appName" value="andor_hbase_qatest" />
			<property name="hbase.zookeeper.quorum"
				value="10.232.98.74,10.232.98.75,10.232.98.76,10.232.98.77,10.232.98.7" />
			<property name="hbase.zookeeper.property.clientPort" value="2181" />
			<property name="zookeeper.znode.parent" value="/hbase-rd-test-0.94" />
		</properties>
	</group>
</matrix>

=== 247687009/tddl/tddl-qatest/src/test/resources/matrix/server_async_topology.xml
<?xml version="1.0" encoding="UTF-8"?>
<matrix name="test_matrix" xmlns="https://github.com/tddl/tddl/schema/matrix"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://github.com/tddl/tddl/schema/matrix https://raw.github.com/tddl/tddl/master/tddl-common/src/main/resources/META-INF/matrix.xsd">

	<group name="andor_group_0">
		<atom name="andor_group_0_atom0" ip="localhost" port="9900"
			status="R10" user-name="should not be here" password="should not be here"
			channelTimeout="2000000" />
		<atom name="andor_group_0_atom1" ip="localhost" port="9901"
			status="R10" user-name="should not be here" password="should not be here"
			channelTimeout="2000000" />
		<atom name="andor_group_0_atom2" ip="localhost" port="9902"
			status="R10" user-name="should not be here" password="should not be here"
			channelTimeout="2000000" />
	</group>

	<group name="andor_group_1">
		<atom name="andor_group_1_atom0" ip="localhost" port="9910"
			status="R10" user-name="should not be here" password="should not be here"
			channelTimeout="2000000" />
		<atom name="andor_group_1_atom1" ip="localhost" port="9911"
			status="R10" user-name="should not be here" password="should not be here"
			channelTimeout="2000000" />
		<atom name="andor_group_1_atom2" ip="localhost" port="9912"
			status="R10" user-name="should not be here" password="should not be here"
			channelTimeout="2000000" />
	</group>

	<group name="andor_group_2">
		<atom name="andor_group_2_atom0" ip="localhost" port="9920"
			status="R10" user-name="should not be here" password="should not be here"
			channelTimeout="2000000" />
		<atom name="andor_group_2_atom1" ip="localhost" port="9921"
			status="R10" user-name="should not be here" password="should not be here"
			channelTimeout="2000000" />
	</group>

	<group name="andor_group_oneAtom">
		<atom name="andor_group_atom" ip="localhost" port="9930" status="R10"
			user-name="should not be here" password="should not be here"
			channelTimeout="2000000" />
	</group>

	<!-- mysql group -->

	<group name="andor_mysql_group_0" type="my_async_jdbc" my_groupName="andor_mysql_group_0"
		my_appName="andor_mysql_qatest">
	</group>

	<group name="andor_mysql_group_1" type="my_async_jdbc" my_groupName="andor_mysql_group_1"
		my_appName="andor_mysql_qatest">
	</group>

	<group name="andor_mysql_group_2" type="my_async_jdbc" my_groupName="andor_mysql_group_2"
		my_appName="andor_mysql_qatest">
	</group>

	<group name="andor_mysql_group_oneAtom" type="my_async_jdbc"
		my_groupName="andor_mysql_group_0" my_appName="andor_mysql_qatest">
		<!-- <atom name="andor_mysql_group_atom" ip="localhost" port="9830" status="R10" 
			user-name="should not be here" password="should not be here" channelTimeout="2000000" 
			/> -->
	</group>
	
	<!-- tdhs group -->
	<group name="andor_tdhs_group_0" type="TDHS_CLIENT" my_groupName="andor_tdhs_group_0"
		my_appName="andor_tdhs_qatest">
	</group>

	<group name="andor_tdhs_group_1" type="TDHS_CLIENT" my_groupName="andor_tdhs_group_1"
		my_appName="andor_tdhs_qatest">
	</group>

	<group name="andor_tdhs_group_2" type="TDHS_CLIENT" my_groupName="andor_tdhs_group_2"
		my_appName="andor_tdhs_qatest">
	</group>
   <group name="andor_tdhs_group_atom" type="TDHS_CLIENT" my_groupName="andor_tdhs_group_atom"
      my_appName="andor_tdhs_qatest">
   </group>

</machine-tapologic>
